Repository mzmine/mzmine, pull requests merged in 2024-01, with the labels that each got.

#586 Default StringParameter empty instead of null
  src/main/java/io/github/mzmine/parameters/parametertypes/FormulaParameter.java
  src/main/java/io/github/mzmine/parameters/parametertypes/StringParameter.java
  src/main/java/io/github/mzmine/parameters/parametertypes/SumformulaParameter.java
Labels: priority_high, workload_low

#1467 Remove classes as keys - memory leaks
  src/main/java/io/github/mzmine/datamodel/features/FeatureList.java
  src/main/java/io/github/mzmine/datamodel/features/ModularDataModel.java
  src/main/java/io/github/mzmine/datamodel/features/ModularFeature.java
  src/main/java/io/github/mzmine/datamodel/features/ModularFeatureList.java
  src/main/java/io/github/mzmine/datamodel/features/ModularFeatureListRow.java
  src/main/java/io/github/mzmine/datamodel/features/SimpleModularDataModel.java
  src/main/java/io/github/mzmine/datamodel/features/types/DataTypes.java
  src/main/java/io/github/mzmine/datamodel/features/types/ListWithSubsType.java
  src/main/java/io/github/mzmine/datamodel/features/types/abstr/SimpleSubColumnsType.java
  src/main/java/io/github/mzmine/datamodel/features/types/annotations/CompoundDatabaseMatchesType.java
  src/main/java/io/github/mzmine/datamodel/features/types/annotations/GNPSSpectralLibraryMatchesType.java
  src/main/java/io/github/mzmine/datamodel/features/types/annotations/LipidMatchListType.java
  src/main/java/io/github/mzmine/datamodel/features/types/annotations/ManualAnnotationType.java
  src/main/java/io/github/mzmine/datamodel/features/types/annotations/SpectralLibraryMatchesType.java
  src/main/java/io/github/mzmine/datamodel/features/types/annotations/formula/FormulaListType.java
  src/main/java/io/github/mzmine/datamodel/features/types/annotations/iin/IonIdentityListType.java
  src/main/java/io/github/mzmine/datamodel/features/types/numbers/SimpleStatisticsType.java
  src/main/java/io/github/mzmine/datamodel/identities/iontype/IonIdentity.java
  src/main/java/io/github/mzmine/main/MZmineCore.java
  src/main/java/io/github/mzmine/main/impl/MZmineConfigurationImpl.java
  src/main/java/io/github/mzmine/modules/dataprocessing/align_append_rows/MergeAlignerTask.java
  src/main/java/io/github/mzmine/modules/dataprocessing/align_lcimage/LcImageAlignerParameters.java
  src/main/java/io/github/mzmine/modules/dataprocessing/align_lcimage/LcImageAlignerTask.java
  src/main/java/io/github/mzmine/modules/dataprocessing/filter_blanksubtraction/FeatureListBlankSubtractionTask.java
  src/main/java/io/github/mzmine/modules/dataprocessing/filter_clearannotations/ClearFeatureAnnotationsTask.java
  src/main/java/io/github/mzmine/modules/dataprocessing/filter_isotopefinder/IsotopeFinderTask.java
  src/main/java/io/github/mzmine/modules/io/export_features_csv/CSVExportModularTask.java
  src/main/java/io/github/mzmine/modules/io/export_features_csv_legacy/LegacyCSVExportTask.java
  src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableFX.java
  src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableFXMLTabAnchorPaneController.java
  src/main/java/io/github/mzmine/util/DataTypeUtils.java
  src/main/java/io/github/mzmine/util/FeatureListUtils.java
  src/main/java/io/github/mzmine/util/FeatureUtils.java
  src/main/java/io/github/mzmine/util/spectraldb/entry/SpectralLibrary.java
  src/test/java/IonIdentityTest.java
  src/test/java/io/github/mzmine/util/FeatureListUtilsTest.java
Labels: core, priority_high, testing_medium

#1468 Batch - error on missing modules
  src/main/java/io/github/mzmine/modules/batchmode/BatchComponentController.java
  src/main/java/io/github/mzmine/modules/batchmode/BatchModeModule.java
  src/main/java/io/github/mzmine/modules/batchmode/BatchQueue.java
  src/main/java/io/github/mzmine/modules/batchmode/BatchQueueParameter.java
  src/main/java/io/github/mzmine/modules/io/projectload/version_3_0/RawDataFileOpenHandler_3_0.java
Labels: priority_high, workload_low

#1613 Dont allow multivariate curve resolution module on macos
  src/main/java/io/github/mzmine/modules/dataprocessing/adap_mcr/ADAP3DecompositionV2Parameters.java
  src/main/java/io/github/mzmine/modules/dataprocessing/adap_mcr/ADAPMultivariateCurveResolutionModule.java
Labels: bug
